spring:
  application:
    name: invitation

  datasource:
    url: jdbc:mariadb://ysjee141-edu.cjsssaa4seds.ap-northeast-2.rds.amazonaws.com:3306/edu?autoReconnect=true
    username: admin
    password: ysjee141-edu
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      show-sql: true
      database: mysql
      properties:
        hibernate:
          format_sql: true # SQL ???
          highlight_sql: true # ANSI ??? ?? ????
          use_sql_comments: true # SQL ??? /* */ ?? ??

logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??